### ISSUE TITLE
是否支持参数传入？

### ISSUE THREAD

**Issue by StrollStars** [cxasm/cc-compare#1]
主要是想搭配TC使用，如果能够支持左右窗口参数传入，用起来会更方便。

PS：软件的联网是用来检测更新吗？可否提供开关的选项？

**Comment by cxasm** [comment]
是可以的，配合svn对比也行。
"C:\Program Files\CCompare\CCompare.exe" -left "%1"
"C:\Program Files\CCompare\CCompare.exe" -right "%1"

或者直接两个文件路径
"C:\Program Files\CCompare\CCompare.exe" "%1"  “%2”

注意目前都是全路径，可能不支持相对路径。

**Comment by chendijun527** [comment]
> 是可以的，配合svn对比也行。 "C:\Program Files\CCompare\CCompare.exe" -left "%1" "C:\Program Files\CCompare\CCompare.exe" -right "%1"
> 
> 或者直接两个文件路径 "C:\Program Files\CCompare\CCompare.exe" "%1" “%2”
> 
> 注意目前都是全路径，可能不支持相对路径。

2个文件夹对比要加上什么参数呢？我用文件的方式会变成bin二进制对比

**Comment by cxasm** [comment]
目录的对比命令如下：
"C:\Program Files\CCompare\CCompare.exe" -leftd "%1"
"C:\Program Files\CCompare\CCompare.exe" -rightd "%1"

需要调用两次，先调用左边目录，再调用右边目录。但是这样可能会新启动一个进程。

**Comment by StrollStars** [comment]
@cxasm 不好意思，测试没成功，可否像文件参数那样连写，然后程序自行判断是文件还是目录？

PS1：github比gitee慢一个版本，也缺少免安装版本。
PS2：希望程序文件能放在可执行文件所在目录。

**Comment by cxasm** [comment]
https://github.com/cxasm/cc-compare/releases/download/v1.16/CCompare-v1.18-x64-Installer.exe

发布了1.18.新增了文件夹对比命令行：

1.18 的文件夹命令行是 -d "dir1path" "dir2path"
