### ISSUE TITLE
被点名了啊！小心当肉鸡

### ISSUE THREAD

**Issue by poijsda** [cxasm/cc-compare#3]
https://twitter.com/cloudwu/status/1620252520533864448

**Comment by 7heaven** [comment]
打印了里面同名的两个dll文件没发现依赖ws2_32.dll啊, 修改了吗？

**Comment by cxasm** [comment]
这是基于QT512.10的代码，QT里面本来就依赖这个库。拜托个别大牛，搞明白再下结论。
