### ISSUE TITLE
如何添加过滤器，过滤目录下不想参于比较的子目录？

### ISSUE THREAD

**Issue by shengnoah** [cxasm/cc-compare#5]
请问，如何添加过滤器，过滤目录下不想参于比较的子目录？
这样在导入目录文件夹的时候，就是不导入，或者不参于比较，提高载入和比较的速度。

**Comment by cxasm** [comment]
![image](https://user-images.githubusercontent.com/42246867/217990418-00b7b988-f895-45e4-b8eb-4eaafff148b7.png)

**Comment by shengnoah** [comment]
> ![image](https://user-images.githubusercontent.com/42246867/217990418-00b7b988-f895-45e4-b8eb-4eaafff148b7.png)

多谢老师，收到！
